// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_RDlb3-Q0Rl2YNQGD9KZPz9CCpm0CZhM',
    appId: '1:687009273156:web:226267fae17d3d4d6d7311',
    messagingSenderId: '687009273156',
    projectId: 'phone-directory-a7c9e',
    authDomain: 'phone-directory-a7c9e.firebaseapp.com',
    storageBucket: 'phone-directory-a7c9e.appspot.com',
    measurementId: 'G-4GBXQSJYBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFabfeyXDplAv0VDA6LIfQP6cYBcX6rq0',
    appId: '1:687009273156:android:798efb0fa660dcc46d7311',
    messagingSenderId: '687009273156',
    projectId: 'phone-directory-a7c9e',
    storageBucket: 'phone-directory-a7c9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdV3hDlkPMeKeD4Y6IjYEh39h9eqjUoy4',
    appId: '1:687009273156:ios:3f136e724960059f6d7311',
    messagingSenderId: '687009273156',
    projectId: 'phone-directory-a7c9e',
    storageBucket: 'phone-directory-a7c9e.appspot.com',
    androidClientId: '687009273156-k9tmumotvc70qqnotrh4k12btam6hs1a.apps.googleusercontent.com',
    iosClientId: '687009273156-6vg1mvtu0l01ctngini28b74stmkvdit.apps.googleusercontent.com',
    iosBundleId: 'com.teispace.phoneDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdV3hDlkPMeKeD4Y6IjYEh39h9eqjUoy4',
    appId: '1:687009273156:ios:3f136e724960059f6d7311',
    messagingSenderId: '687009273156',
    projectId: 'phone-directory-a7c9e',
    storageBucket: 'phone-directory-a7c9e.appspot.com',
    androidClientId: '687009273156-k9tmumotvc70qqnotrh4k12btam6hs1a.apps.googleusercontent.com',
    iosClientId: '687009273156-6vg1mvtu0l01ctngini28b74stmkvdit.apps.googleusercontent.com',
    iosBundleId: 'com.teispace.phoneDirectory',
  );
}
